markdown: kramdown
baseurl: /jekyll-oni
url: http://orchid-blossom.cloudvent.net
website-title: John Smith
website-description:
website-author: John Smith
exclude: ['README.md', '.gitignore']
permalink: pretty
social:
  - provider: facebook
    account-id: '#'
  - provider: instagram
    account-id: '#'
  - provider: twitter
    account-id: '#'
include-analytics-tracking: true
google-api-key:
analytics:
  provider: google
  google:
    tracking_id:
collections:
  albums:
    output: true
    permalink: /works/:path/
gems: [
    jekyll-paginate,
    jekyll/tagging,
    jekyll-tagging-related_posts
  ]
disqus:
  comments: true
  url: demodchantzis.disqus.com
instagram-feed: false
display-social-media-share-buttons: true
paginate: 5
paginate_path: "/news/page:num/"
contact-info:
  name: John Smith
  job-title: Artist
  e-mail: demo.email@demo.smth
  phone: +44 (0) 040021130
  website-url: http://www.demo-something.com
  address:
      street: Street
      locality: Locality
      region: Region
      country: Country
      postal-code: Post code
